### ISSUE TITLE
Frontpage hero picture

### ISSUE THREAD

**Issue by raae** [lillylabs/little-lilly-website#13]
Either css overlay or photoshop filter file needed.

PS: New photos will be taken late july

**Comment by raae** [comment]
Photo needed before "Ready for next stage"

**Comment by raae** [comment]
Hero image added to index.md

**Comment by raae** [comment]
It would be great if you could do this next @davidtmiller, its an eyesore.

**Comment by davidtmiller** [comment]
Completed in #17

**Comment by raae** [comment]
Is it possibles to get more of the soft/blurred feeling as in the Creative image with css?

**Comment by davidtmiller** [comment]
On this one I created a custom project variable called $brand-background which sets a different background color other than $brand-dark that get's faded out. The color now matches the image on the Creative theme, but if you want a soft blur you will need to filter the original photo on Photoshop.

**Comment by davidtmiller** [comment]
See above message. Other than the blur this is completed in #20!
