### ISSUE TITLE
Creative themed version of Velocity's contact us page

### ISSUE THREAD

**Issue by raae** [lillylabs/little-lilly-website#3]
The Velocity page: http://themes.3rdwavemedia.com/velocity/1.5.6/contact.html

**Comment by raae** [comment]
Needs content before "ready for next stage"

**Comment by raae** [comment]
Example content added to contact.md

**Comment by raae** [comment]
Skip the map section.

**Comment by davidtmiller** [comment]
Initial form styles completed in #17

**Comment by raae** [comment]
Is is possible to make it pretty even with labels? It makes for better ux.

**Comment by davidtmiller** [comment]
Completed in #20! Notice I also added a new icon set called Simple Line Icons. I am using those icons on the home page features sections and on the contact page. These icons are a little more distinct and will differentiate your site a bit more from other ones - I like the design of them a bit better. They only took a few seconds to add so it wasn't a time commitment at all. You can check out the docs and demo here: https://github.com/thesabbir/simple-line-icons - I hope you like them!

**Comment by raae** [comment]
Great! I like them.
